# Generated by Django 5.2.16 on 2026-07-14 09:53

import uuid
from django.db import migrations, models


def backfill_usernames(apps, schema_editor):
    """Give existing employees a unique placeholder username so the unique constraint is satisfied."""
    Employee = apps.get_model('core', 'Employee')
    for emp in Employee.objects.all():
        emp.username = f"emp_{emp.id}_{uuid.uuid4().hex[:6]}"
        emp.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Add password_hash first (no uniqueness issue)
        migrations.AddField(
            model_name='employee',
            name='password_hash',
            field=models.CharField(default='', max_length=256),
        ),
        # Add username without unique=True first
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
        # Backfill unique placeholders for existing rows
        migrations.RunPython(backfill_usernames, migrations.RunPython.noop),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
