# Generated by Django 5.2.16 on 2026-07-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_password_hash_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='break_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the current break expires (status=ON_BREAK)', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('ASSIGNED', 'Assigned'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('ON_BREAK', 'On Break'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=15),
        ),
    ]
