# Generated by Django 5.2.16 on 2026-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_break_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='video_source',
            field=models.CharField(blank=True, default='', help_text='Path or URL for the video/feed assigned to this zone', max_length=255),
        ),
    ]
